"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os

# Получаем версию из app/__version__.py
version = {}
with open(os.path.join("app", "__version__.py")) as f:
    exec(f.read(), version)
APP_VERSION = version["__version__"]

APP = ['main.py']
DATA_FILES = [
    ('assets', [
        'assets/icon_idle.png',
        'assets/icon_recording.png',
        'assets/icon_processing.png',
        'assets/icon_error.png',
        'assets/app_icon.icns.icns'
    ]),
]

# Проверяем наличие ffmpeg
if os.path.exists('bin/ffmpeg_x86_64'):
    DATA_FILES.append(('bin', ['bin/ffmpeg_x86_64']))
if os.path.exists('bin/ffmpeg_arm64'):
    DATA_FILES.append(('bin', ['bin/ffmpeg_arm64']))
if os.path.exists('bin/ffmpeg'):
    DATA_FILES.append(('bin', ['bin/ffmpeg']))

OPTIONS = {
    'argv_emulation': True,
    'plist': {
        'LSUIElement': True,
        'CFBundleName': "Steno",
        'CFBundleDisplayName': "Steno",
        'CFBundleIdentifier': "com.sergeygalay.steno",
        'CFBundleVersion': APP_VERSION,
        'CFBundleShortVersionString': APP_VERSION,
        'NSMicrophoneUsageDescription': "Приложение записывает звук микрофона во время встреч.",
        'NSScreenCaptureUsageDescription': "Приложение записывает экран для сохранения видео встреч.",
    },
    'packages': ['PyQt6', 'certifi', 'objc', 'AVFoundation', 'Quartz', 'CoreMedia', 'ScreenCaptureKit', 'ApplicationServices', 'AppKit', 'Foundation', 'qtawesome', 'markdown', 'app', 'sounddevice', 'numpy', 'charset_normalizer'],
    'includes': ['google.genai', 'html.parser'],
    'excludes': ['tkinter', '_tkinter'],
    'iconfile': 'assets/app_icon.icns.icns',
}

setup(
    app=APP,
    name="Steno",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
